package cnk.air_commercialscalculationengine.settlementrules;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class AdvancedDefinition implements java.io.Serializable
{


	public boolean checkFareBasisValue(String fareBasis, String checkfareBasisValue, String fareBasisValue) {
		
		if(fareBasisValue!=null) {
			
			if (fareBasis.equals("STARTSWITH") && fareBasisValue.startsWith(checkfareBasisValue)) 
				return true;
			
			else if (fareBasis.equals("ENDSWITH") && fareBasisValue.endsWith(checkfareBasisValue)) 
				return true;
			
			else if (fareBasis.equals("CONTAINS") && fareBasisValue.contains(checkfareBasisValue))
				return true;
			
			else if (fareBasis.equals("EQUALTO") && fareBasisValue.equals(checkfareBasisValue))
				return true;
		}

		return false;
	}
   static final long serialVersionUID = 1L;

   private boolean isAdvanceDefinition;
   private java.util.Date ticketingDate;
   private java.util.Date travelDate;
   private java.lang.String travelType;
   private java.lang.String journeyType;
   private java.lang.String flightType;
   private java.lang.String flightLineType;
   private boolean codeShareFlightIncluded;
   private java.lang.String travelProductName;
   private java.lang.String fromContinent;
   private java.lang.String fromCountry;
   private java.lang.String fromCity;
   private java.lang.String viaContinent;
   private java.lang.String viaCountry;
   private java.lang.String viaCity;
   private java.lang.String toContinent;
   private java.lang.String toCountry;
   private java.lang.String toCity;
   private java.lang.String connectivitySupplier;
   private java.lang.String connectivitySupplierType;
   private java.lang.String cabinClass;
   private java.lang.String fareBasisValue;
   private java.lang.String dealCode;
   private java.lang.String credentialsName;
   private java.lang.String bookingType;

   private java.lang.String RBD;

   public AdvancedDefinition()
   {
   }

   public boolean isIsAdvanceDefinition()
   {
      return this.isAdvanceDefinition;
   }

   public void setIsAdvanceDefinition(boolean isAdvanceDefinition)
   {
      this.isAdvanceDefinition = isAdvanceDefinition;
   }

   public java.util.Date getTicketingDate()
   {
      return this.ticketingDate;
   }

   public void setTicketingDate(java.util.Date ticketingDate)
   {
      this.ticketingDate = ticketingDate;
   }

   public java.util.Date getTravelDate()
   {
      return this.travelDate;
   }

   public void setTravelDate(java.util.Date travelDate)
   {
      this.travelDate = travelDate;
   }

   public java.lang.String getTravelType()
   {
      return this.travelType;
   }

   public void setTravelType(java.lang.String travelType)
   {
      this.travelType = travelType;
   }

   public java.lang.String getJourneyType()
   {
      return this.journeyType;
   }

   public void setJourneyType(java.lang.String journeyType)
   {
      this.journeyType = journeyType;
   }

   public java.lang.String getFlightType()
   {
      return this.flightType;
   }

   public void setFlightType(java.lang.String flightType)
   {
      this.flightType = flightType;
   }

   public java.lang.String getFlightLineType()
   {
      return this.flightLineType;
   }

   public void setFlightLineType(java.lang.String flightLineType)
   {
      this.flightLineType = flightLineType;
   }

   public boolean isCodeShareFlightIncluded()
   {
      return this.codeShareFlightIncluded;
   }

   public void setCodeShareFlightIncluded(boolean codeShareFlightIncluded)
   {
      this.codeShareFlightIncluded = codeShareFlightIncluded;
   }

   public java.lang.String getTravelProductName()
   {
      return this.travelProductName;
   }

   public void setTravelProductName(java.lang.String travelProductName)
   {
      this.travelProductName = travelProductName;
   }

   public java.lang.String getFromContinent()
   {
      return this.fromContinent;
   }

   public void setFromContinent(java.lang.String fromContinent)
   {
      this.fromContinent = fromContinent;
   }

   public java.lang.String getFromCountry()
   {
      return this.fromCountry;
   }

   public void setFromCountry(java.lang.String fromCountry)
   {
      this.fromCountry = fromCountry;
   }

   public java.lang.String getFromCity()
   {
      return this.fromCity;
   }

   public void setFromCity(java.lang.String fromCity)
   {
      this.fromCity = fromCity;
   }

   public java.lang.String getViaContinent()
   {
      return this.viaContinent;
   }

   public void setViaContinent(java.lang.String viaContinent)
   {
      this.viaContinent = viaContinent;
   }

   public java.lang.String getViaCountry()
   {
      return this.viaCountry;
   }

   public void setViaCountry(java.lang.String viaCountry)
   {
      this.viaCountry = viaCountry;
   }

   public java.lang.String getViaCity()
   {
      return this.viaCity;
   }

   public void setViaCity(java.lang.String viaCity)
   {
      this.viaCity = viaCity;
   }

   public java.lang.String getToContinent()
   {
      return this.toContinent;
   }

   public void setToContinent(java.lang.String toContinent)
   {
      this.toContinent = toContinent;
   }

   public java.lang.String getToCountry()
   {
      return this.toCountry;
   }

   public void setToCountry(java.lang.String toCountry)
   {
      this.toCountry = toCountry;
   }

   public java.lang.String getToCity()
   {
      return this.toCity;
   }

   public void setToCity(java.lang.String toCity)
   {
      this.toCity = toCity;
   }

   public java.lang.String getConnectivitySupplier()
   {
      return this.connectivitySupplier;
   }

   public void setConnectivitySupplier(java.lang.String connectivitySupplier)
   {
      this.connectivitySupplier = connectivitySupplier;
   }

   public java.lang.String getConnectivitySupplierType()
   {
      return this.connectivitySupplierType;
   }

   public void setConnectivitySupplierType(
         java.lang.String connectivitySupplierType)
   {
      this.connectivitySupplierType = connectivitySupplierType;
   }

   public java.lang.String getCabinClass()
   {
      return this.cabinClass;
   }

   public void setCabinClass(java.lang.String cabinClass)
   {
      this.cabinClass = cabinClass;
   }

   public java.lang.String getFareBasisValue()
   {
      return this.fareBasisValue;
   }

   public void setFareBasisValue(java.lang.String fareBasisValue)
   {
      this.fareBasisValue = fareBasisValue;
   }

   public java.lang.String getDealCode()
   {
      return this.dealCode;
   }

   public void setDealCode(java.lang.String dealCode)
   {
      this.dealCode = dealCode;
   }

   public java.lang.String getCredentialsName()
   {
      return this.credentialsName;
   }

   public void setCredentialsName(java.lang.String credentialsName)
   {
      this.credentialsName = credentialsName;
   }

   public java.lang.String getBookingType()
   {
      return this.bookingType;
   }

   public void setBookingType(java.lang.String bookingType)
   {
      this.bookingType = bookingType;
   }

   public java.lang.String getRBD()
   {
      return this.RBD;
   }

   public void setRBD(java.lang.String RBD)
   {
      this.RBD = RBD;
   }

   public AdvancedDefinition(boolean isAdvanceDefinition,
         java.util.Date ticketingDate, java.util.Date travelDate,
         java.lang.String travelType, java.lang.String journeyType,
         java.lang.String flightType, java.lang.String flightLineType,
         boolean codeShareFlightIncluded, java.lang.String travelProductName,
         java.lang.String fromContinent, java.lang.String fromCountry,
         java.lang.String fromCity, java.lang.String viaContinent,
         java.lang.String viaCountry, java.lang.String viaCity,
         java.lang.String toContinent, java.lang.String toCountry,
         java.lang.String toCity, java.lang.String connectivitySupplier,
         java.lang.String connectivitySupplierType, java.lang.String cabinClass,
         java.lang.String fareBasisValue, java.lang.String dealCode,
         java.lang.String credentialsName, java.lang.String bookingType,
         java.lang.String RBD)
   {
      this.isAdvanceDefinition = isAdvanceDefinition;
      this.ticketingDate = ticketingDate;
      this.travelDate = travelDate;
      this.travelType = travelType;
      this.journeyType = journeyType;
      this.flightType = flightType;
      this.flightLineType = flightLineType;
      this.codeShareFlightIncluded = codeShareFlightIncluded;
      this.travelProductName = travelProductName;
      this.fromContinent = fromContinent;
      this.fromCountry = fromCountry;
      this.fromCity = fromCity;
      this.viaContinent = viaContinent;
      this.viaCountry = viaCountry;
      this.viaCity = viaCity;
      this.toContinent = toContinent;
      this.toCountry = toCountry;
      this.toCity = toCity;
      this.connectivitySupplier = connectivitySupplier;
      this.connectivitySupplierType = connectivitySupplierType;
      this.cabinClass = cabinClass;
      this.fareBasisValue = fareBasisValue;
      this.dealCode = dealCode;
      this.credentialsName = credentialsName;
      this.bookingType = bookingType;
      this.RBD = RBD;
   }

}