package cnk.air_commercialscalculationengine.settlementrules;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ContentAccessFee implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private cnk.air_commercialscalculationengine.settlementrules.OtherFees otherFees;

   public ContentAccessFee()
   {
   }

   public cnk.air_commercialscalculationengine.settlementrules.OtherFees getOtherFees()
   {
      return this.otherFees;
   }

   public void setOtherFees(
         cnk.air_commercialscalculationengine.settlementrules.OtherFees otherFees)
   {
      this.otherFees = otherFees;
   }

   public ContentAccessFee(
         cnk.air_commercialscalculationengine.settlementrules.OtherFees otherFees)
   {
      this.otherFees = otherFees;
   }

}