package cnk.air_commercialscalculationengine.settlementrules;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class PenaltyFee implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String contractType;
   private java.util.List<cnk.air_commercialscalculationengine.settlementrules.SlabDetails> slabDetails;
   private double minimumtoAchieve;
   private double commercialAmount;
   private java.lang.String commercialCurrency;
   private java.lang.String commercialType;
   private boolean isApplicable;

   private double percentageValue;

   public PenaltyFee()
   {
   }

   public java.lang.String getContractType()
   {
      return this.contractType;
   }

   public void setContractType(java.lang.String contractType)
   {
      this.contractType = contractType;
   }

   public java.util.List<cnk.air_commercialscalculationengine.settlementrules.SlabDetails> getSlabDetails()
   {
      return this.slabDetails;
   }

   public void setSlabDetails(
         java.util.List<cnk.air_commercialscalculationengine.settlementrules.SlabDetails> slabDetails)
   {
      this.slabDetails = slabDetails;
   }

   public double getMinimumtoAchieve()
   {
      return this.minimumtoAchieve;
   }

   public void setMinimumtoAchieve(double minimumtoAchieve)
   {
      this.minimumtoAchieve = minimumtoAchieve;
   }

   public double getCommercialAmount()
   {
      return this.commercialAmount;
   }

   public void setCommercialAmount(double commercialAmount)
   {
      this.commercialAmount = commercialAmount;
   }

   public java.lang.String getCommercialCurrency()
   {
      return this.commercialCurrency;
   }

   public void setCommercialCurrency(java.lang.String commercialCurrency)
   {
      this.commercialCurrency = commercialCurrency;
   }

   public java.lang.String getCommercialType()
   {
      return this.commercialType;
   }

   public void setCommercialType(java.lang.String commercialType)
   {
      this.commercialType = commercialType;
   }

   public boolean isIsApplicable()
   {
      return this.isApplicable;
   }

   public void setIsApplicable(boolean isApplicable)
   {
      this.isApplicable = isApplicable;
   }

   public double getPercentageValue()
   {
      return this.percentageValue;
   }

   public void setPercentageValue(double percentageValue)
   {
      this.percentageValue = percentageValue;
   }

   public PenaltyFee(
         java.lang.String contractType,
         java.util.List<cnk.air_commercialscalculationengine.settlementrules.SlabDetails> slabDetails,
         double minimumtoAchieve, double commercialAmount,
         java.lang.String commercialCurrency, java.lang.String commercialType,
         boolean isApplicable, double percentageValue)
   {
      this.contractType = contractType;
      this.slabDetails = slabDetails;
      this.minimumtoAchieve = minimumtoAchieve;
      this.commercialAmount = commercialAmount;
      this.commercialCurrency = commercialCurrency;
      this.commercialType = commercialType;
      this.isApplicable = isApplicable;
      this.percentageValue = percentageValue;
   }

}